"""Structured order types for agent-to-engine communication.

These dataclasses bridge the gap between a signal (from Quant) and
a lumibot ``create_order()`` call, giving the agent a typed contract
for buy/sell decisions.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Literal


@dataclass
class OrderRequest:
    """A buy or sell order ready for submission to the broker (or backtest).

    Generated by :class:`PortfolioEngine.build_order` from a
    signal + risk check + position-size calculation.
    """

    asset: str
    action: Literal["buy", "sell"]
    quantity: int
    order_type: Literal["market", "limit", "stop"] = "market"
    price: float | None = None       # signal-price anchor (not limit price)
    reason: str = ""                  # human-readable rationale
    id: str = ""                      # optional external ID (set by caller)
    metadata: dict = field(default_factory=dict)

    def validate(self) -> bool:
        """Basic sanity checks: valid symbol, positive qty, known action."""
        if not self.asset or not self.asset.strip():
            return False
        if self.quantity <= 0:
            return False
        if self.action not in ("buy", "sell"):
            return False
        return True

    def to_dict(self) -> dict:
        d = {
            "asset": self.asset,
            "action": self.action,
            "quantity": self.quantity,
            "order_type": self.order_type,
            "reason": self.reason,
        }
        if self.price is not None:
            d["price"] = self.price
        if self.metadata:
            d["metadata"] = self.metadata
        return d


@dataclass
class OrderResponse:
    """Acknowledgement / fill report for a submitted order."""

    order_id: str = ""
    asset: str = ""
    action: str = ""
    status: Literal["pending", "filled", "cancelled", "rejected"] = "pending"
    filled_quantity: int = 0
    filled_price: float = 0.0
    message: str = ""

    @property
    def success(self) -> bool:
        return self.status == "filled"

    @classmethod
    def ok(cls, order_id: str, **kw) -> OrderResponse:
        """Create a success response. Extra kwargs are silently dropped."""
        fields = {"order_id", "asset", "action", "status", "filled_quantity",
                  "filled_price", "message"}
        filtered = {k: v for k, v in kw.items() if k in fields}
        return cls(order_id=order_id, status="filled", **filtered)

    @classmethod
    def failure(cls, order_id: str, message: str) -> OrderResponse:
        return cls(order_id=order_id, status="rejected", message=message)
